clientConfig:
    maxConnTotal:    1000
    maxConnPerRoute: 1000
    ignoreSslErrors: true

defaultParams:
    method:          HEAD
    socketTimeout:   30000
    connectTimeout:  30000

sites:

- name:     Google
  url:      http://www.google.com

- name:     AppDynamics
  url:      https://www.appdynamics.com

- name:     Help
  url:      https://help.appdynamics.com

- name:     Demo controller
  url:      http://localhost:8080/controller/rest/applications
  username: user1@customer1
  password: welcome
